# Generated by Django 5.0.7 on 2024-07-23 10:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="decription",
            new_name="description",
        ),
    ]
